
name: Deploy Contoso_University_Core

on:
  workflow_run:
    workflows: ["Pack Contoso_University_Core"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: 'Contoso Staging'
    steps:
      - uses: actions/checkout@v4
      - uses: dawidd6/action-download-artifact@v3
        with:
          workflow: pack-solution-demo.yml
          name: packed-solution
      - uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ vars.POWERPLATFORMORGURI }}
          #user-name: ${{ secrets.USERNAME }}
          #password-secret: ${{ secrets.PASSWORD }}
          app-id: ${{ secrets.CLIENTID }}
          client-secret: ${{ secrets.CLIENTSECRET }}
          tenant-id: ${{ secrets.TENANTID }}
          solution-file: contoso_university_core_managed.zip
          use-deployment-settings-file: true

