name: Export Solution from Dev

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default:  'contoso_university_core'
      branch_name:
        description: 'name of the git branch'
        required: false
        default:  'main'
jobs:
  BootsandCats:
    runs-on: ubuntu-latest
    environment: 'Contoso Development'
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - name: Variables      
      run: |        
        echo "Solution Name : ${{ github.event.inputs.solution_name }}"        
        echo "URI ${{ vars.POWERPLATFORMURI }}"        
        echo "Source ${{ vars.POWERPLATFORMORGURI_DEV }}"   
    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{ vars.POWERPLATFORMORGURI_DEV }}
        app-id: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTID }}
        client-secret: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTSECRET }}
        tenant-id: ${{ secrets.POWERPLATFORMCONTOSOPRODUCTIONTENANTID }}
    - name: Export Unmanaged Solution
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{ vars.POWERPLATFORMORGURI_DEV }}
        app-id: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTID }}
        client-secret: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTSECRET }}
        tenant-id: ${{ secrets.POWERPLATFORMCONTOSOPRODUCTIONTENANTID }}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: 'solutions/${{ github.event.inputs.solution_name }}.zip'
        export-customization-settings: true
        overwrite: true
        managed: false
    - name: Export Managed Solution      
      uses: microsoft/powerplatform-actions/export-solution@v0          
      with:          
        environment-url: ${{ vars.POWERPLATFORMORGURI_DEV }}          
        app-id: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTID }}          
        client-secret: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTSECRET }}         
        tenant-id: ${{ secrets.POWERPLATFORMCONTOSOPRODUCTIONTENANTID }}          
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: 'solutions/${{ github.event.inputs.solution_name }}_managed.zip'          
        export-customization-settings: true
        overwrite: true          
        managed: true
    - name: Unpack Solution
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: solutions/${{ vars.POWERPLATFORMSOLUTIONNAME}}.zip
        solution-folder: src/${{ github.event.inputs.solution_name }}
        solution-type: Both
        process-canvas-apps: true
    - name: Add and Commit to main
      if: ${{ github.event.inputs.branch_name }} == 'main'
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Export Solution ${{ github.event.inputs.solution_name }}'
        add: '. --force'
    - name: Add and Commit to new branch
      if: ${{ github.event.inputs.branch_name }} != 'main'
      uses: EndBug/add-and-commit@v9
      with: 
        message: 'Export Solution ${{ github.event.inputs.solution_name }} to branch ${{ github.event.inputs.branch_name }}'
        new-branch: ${{ github.event.inputs.branch_name }}
        add: '. --force'
