name: Pack Contoso University Core

on:
  push:
    paths:
      - contents/**
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1      
      - uses: microsoft/powerplatform-actions/pack-solution@v1
        with:
          solution-file: out/contoso_university_core.zip
          solution-folder: contents/contoso_university_core
          solution-type: Both
      - uses: actions/upload-artifact@v4
        with: 
          name: packed-solution
          path: out/

  
