name: Pack Contoso_University_Core

on:
  #push:
  #  paths:
  #    - src/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: release/contoso_university_core/contoso_university_core.zip
          solution-folder: src/contoso_university_core
          solution-type: Both
      - uses: actions/upload-artifact@v2
        with:
          name: packed-solution
          path: release/contoso_university_core

