name: Unpack Solution
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Variables
        run: |                  
          echo "Solution Name : ${{ vars.POWERPLATFORMSOLUTIONNAME }}"                  
          echo "URI ${{ vars.POWERPLATFORMURI }}"                  
          echo "Source ${{ vars.POWERPLATFORMSOURCEENVIRONMENT }}"             
          echo "Target ${{ vars.POWERPLATFORMTARGETENVIRONMENT }}"
      - uses: microsoft/powerplatform-actions/unpack-solution@v0
        name: Unpack Solution
        with:
          solution-file: Solutions/${{ vars.POWERPLATFORMSOLUTIONNAME}}.zip
          solution-folder: src/${{ vars.POWERPLATFORMSOLUTIONNAME }}
          solution-type: Both
      - name: Add and Commit
        uses: EndBug/add-and-commit@v9
        with:          
          message: 'Upack Solution ${{ vars.POWERPLATFORMSOLUTIONNAME }}'          
          add: 'src/* --force'
